server:
  port: 8762
  #访问根路径
  context-path: /

spring:
  application:
    #应用程序名称，注意与访问路径无关，通过spring.application.name属性，我们可以指定微服务的名称后续在调用的时候只需要该名字就可以进行服务的访问
    name: service-provider

eureka:
  instance:
    #主机名称,这里使用localhost，主要名要与IP有映射关系
    hostname: localhost
  client:
    #服务提供方 将服务注册到注册中心
    registerWithEureka: true
    #服务提供方不需要从注册中心拉去服务
    fetchRegistry: false
    #服务注册中心地址 指定服务注册中心的位置。
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/
    #启动健康检查
    healthcheck:
        enable: true
