

eureka:
  instance:
    #主机名称
    hostname: localhost
    #Eureka服务器在接收到实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除，默认为90秒
    lease-expiration-duration-in-seconds: 30
    #eureka客户需要每隔多长时间发送心跳给eureka服务器，表明它仍然活着,默认为30 秒
    lease-renewal-interval-in-seconds: 30
  client:
    #实例是否在eureka服务器上注册自己的信息以供其他服务发现，默认为true,在这里该应用仅为注册中心，不提供服务,因此设置成false
    registerWithEureka: false
    #此客户端是否获取eureka服务器注册表上的注册信息，默认为true，因为在这里该应用仅为注册中心，不访问eureka服务，所以设置成false
    fetchRegistry: false
    #Eureka服务注册中心地址
    serviceUrl:
            defaultZone: http://localhost:8761/eureka/
  server:
    # 自我保护模式，当出现出现网络分区、eureka在短时间内丢失过多客户端时，会进入自我保护模式，即一个服务长时间没有发送心跳，eureka也不会将其删除，默认为true
    enable-self-preservation: false

